# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Nostalgia del Reino"



author:
  name:             Juan Ignacio Gil Gómez
  twitter:          JuanIgnacioGil
  github:           JuanIgnacioGil
  linkedin:         juanignaciogilgomez
  email:            mail@nostalgiadelreino.net

# Google-analytics
google-analytics:
  id:               "1911323"

# Disqus
disqus:
  id:               "nostalgiadelreino"

# URL
url:                "http://nostalgiadelreino.net/"

baseurl:            ""


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/London
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/juanignaciogil/nostalgiadelreino"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
